# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  amd64: "ghcr.io/home-assistant/amd64-base-debian:3.15"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Reactive home"
  org.opencontainers.image.description: "Reactive home automation runtime for home assistant."
  org.opencontainers.image.source: "https://github.com/TheNoim/reactive-home"
  org.opencontainers.image.licenses: "MIT"
args:
  DENO_VERSION: "1.29.2"
