name: "Reactive Home"
description: "Reactive home automation runtime for home assistant"
version: "0.3.6"
slug: "reactive_home"
init: false
image: "ghcr.io/thenoim/reactive-home"
arch:
  - amd64
homeassistant_api: true
map:
  - config:rw
