# This is a basic workflow to help you get started with Actions

name: release-it

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  publish:
    runs-on: ubuntu-latest

    if: "!startsWith(github.event.head_commit.message, 'chore(release): ')"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configuring Git and NPM
        run: |
          git config --global user.name "Nils Bergmann"
          git config --global user.email "nilsbergmann@noim.io"

      - uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Installing dependencies
        run: npm install

      - name: Release It
        run: npm run release
        env:
          GITHUB_TOKEN: ${{ github.token }}
